//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StephManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StephManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0000_subir_imagen {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0000_subir-imagen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0000_subir_imagen_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0000_subir-imagen-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0001_agregar {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0001_agregar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0001_agregar_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0001_agregar-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0002_cancelar {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0002_cancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0002_cancelar_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0002_cancelar-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0003_guardar {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0003_guardar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0003_guardar_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0003_guardar-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0004_eliminar {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0004_eliminar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0004_eliminar_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0004_eliminar-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0005_modificar {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0005_modificar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0005_modificar_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0005_modificar-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0006_regresr {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0006_regresr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0000s_0006_regresr_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0000s_0006_regresr-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0000_salir {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0000_salir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0000_salir_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0000_salir-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0001_web {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0001_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0001_web_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0001_web-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0002_compras {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0002_compras", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0002_compras_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0002_compras-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0003_tarjeta {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0003_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0003_tarjeta_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0003_tarjeta-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0004_notificaciones {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0004_notificaciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0004_notificaciones_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0004_notificaciones-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0005_checador {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0005_checador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0005_checadora_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0005_checadora-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0006_mobiliario {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0006_mobiliario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0006_mobiliarioa_ {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0006_mobiliarioa-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0007_vales {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0007_vales", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0007_valesa_ {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0007_valesa-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0008_cursos {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0008_cursos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0008_cursos_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0008_cursos-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0009_cuestionarios {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0009_cuestionarios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0009_cuestionarios_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0009_cuestionarios-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0010_citas {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0010_citas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0010_citas_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0010_citas-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0011_gastos {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0011_gastos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0011_gastos_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0011_gastos-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0012_configuraciones {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0012_configuraciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0012_configuraciones_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0012_configuraciones-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0013_pedido {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0013_pedido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0013_pedido_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0013_pedido-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0014_catalogo {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0014_catalogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0014_catalogo_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0014_catalogo-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0015_inventario {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0015_inventario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0015_inventarioa_ {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0015_inventarioa-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0016_comisiones {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0016_comisiones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0016_comisiones_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0016_comisiones-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0017_nomina {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0017_nomina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0017_nomina_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0017_nomina-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0018_empleado {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0018_empleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0018_empleado_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0018_empleado-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0019_clientes {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0019_clientes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0019_clientes_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0019_clientes-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0020_servicios {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0020_servicios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0020_servicios_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0020_servicios-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0021_productos {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0021_productos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0022_login_ok {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0022_login ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0000s_0001s_0022_login_ok_a {
            get {
                object obj = ResourceManager.GetObject("0000s_0001s_0022_login ok-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activiades {
            get {
                object obj = ResourceManager.GetObject("activiades", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actividades_N {
            get {
                object obj = ResourceManager.GetObject("actividades-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checar {
            get {
                object obj = ResourceManager.GetObject("checar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checar_a {
            get {
                object obj = ResourceManager.GetObject("checar-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checklist {
            get {
                object obj = ResourceManager.GetObject("checklist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checklist_N {
            get {
                object obj = ResourceManager.GetObject("checklist-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0006_activar_curso {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0006_activar-curso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0006_activar_curso_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0006_activar-curso-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0007_transferencias {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0007_transferencias", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0007_transferencias_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0007_transferencias-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0008_excel {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0008_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0008_excel_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0008_excel-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0009_imprimir {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0009_imprimir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0009_imprimir_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0009_imprimir-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0010_saldo_monedero {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0010_saldo-monedero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro___0010_saldo_monedero_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro--_0010_saldo-monedero-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro_0000s_0001s_0021_productos_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-negro_0000s_0001s_0021_productos-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro_caja {
            get {
                object obj = ResourceManager.GetObject("icons steph negro-caja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro_caja_a {
            get {
                object obj = ResourceManager.GetObject("icons steph negro-caja-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_negro_descargar_formato {
            get {
                object obj = ResourceManager.GetObject("icons steph negro-descargar formato", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0011_monedero {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0011_monedero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0011_monedero_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0011_monedero-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0012_evaluación {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0012_evaluación", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0012_evaluación_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0012_evaluación-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0014_cursos_copy_4 {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0014_cursos-copy-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0014_cursos_copy_4_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0014_cursos-copy-4-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0016_concluir_curso {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0016_concluir-curso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0016_concluir_curso_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0016_concluir-curso-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0017_inscripcion_cursos {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0017_inscripcion-cursos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino___0017_inscripcion_cursos_a {
            get {
                object obj = ResourceManager.GetObject("icons-steph-vino--_0017_inscripcion-cursos-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_asignar_horario {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-asignar horario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_asignar_horario_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-asignar horario-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_Atender_Cita {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-Atender Cita", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_Atender_Cita_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-Atender Cita-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_checador_justificacion {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-checador-justificacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_checador_justificacion_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-checador-justificacion-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_citas_cancelar_cita {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-citas-cancelar-cita", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_citas_cancelar_cita_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-citas-cancelar-cita-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_compra_mobiliario_procesar_mobiliario {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-compra mobiliario-procesar-mobiliario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_compra_mobiliario_procesar_mobiliario_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-compra mobiliario-procesar-mobiliario-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_compras_pagar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-compras-pagar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_compras_pagar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-compras-pagar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_compras_procesar_compra {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-compras-procesar-compra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_compras_procesar_compra_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-compras-procesar-compra-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_cuestionario_activar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-cuestionario-activar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_cuestionario_activar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-cuestionario-activar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_cuestionario_cancelar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-cuestionario-cancelar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_cuestionario_cancelar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-cuestionario-cancelar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_descontar_existencias {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-descontar existencias", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_descontar_existencias_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-descontar existencias-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_asignar_categoria {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-asignar-categoria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_asignar_categoria_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-asignar-categoria-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_captura_huella {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-captura-huella", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_captura_huella_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-captura-huella-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_cuenta_usuario {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-cuenta-usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_cuenta_usuario_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-cuenta-usuario-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_historial_laboral {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-historial-laboral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_historial_laboral_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-historial-laboral-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_nomina_alta {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-nomina-alta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_nomina_alta_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-nomina-alta-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_nomina_baja {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-nomina-baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_nomina_baja_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-nomina-baja-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_permiso {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-permiso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_permiso_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-permiso-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_vacaciones {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-vacaciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_empleado_vacaciones_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-empleado-vacaciones-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_enviar_pedido {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-enviar pedido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_enviar_pedido_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-enviar pedido-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_inventario_ajustes {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-inventario-ajustes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_inventario_ajustes_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-inventario-ajustes-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_inventario_stock {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-inventario-stock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_inventario_stock_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-inventario-stock-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_leer_inventario {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-leer inventario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_leer_inventario_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-leer inventario-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_mobiliario_baja {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-mobiliario-baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_mobiliario_baja_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-mobiliario-baja-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_mobiliario_pago_compras_cancelar_pagos {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-mobiliario pago compras-cancelar-pagos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_mobiliario_pago_compras_cancelar_pagos_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-mobiliario pago compras-cancelar-pagos-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_mobiliario_resguardo {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-mobiliario-resguardo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_mobiliario_resguardo_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-mobiliario-resguardo-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nomina_fechas_continuar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nomina fechas-continuar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nomina_fechas_continuar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nomina fechas-continuar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nomina_reporte_detalle {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nomina-reporte-detalle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nomina_reporte_detalle_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nomina-reporte-detalle-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nomina_reporte_saldo {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nomina-reporte-saldo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nomina_reporte_saldo_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nomina-reporte-saldo-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_notificaciones_reenviar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-notificaciones-reenviar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_notificaciones_reenviar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-notificaciones-reenviar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nuevo_nomina_generar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nuevo-nomina-generar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_nuevo_nomina_generar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-nuevo-nomina-generar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_pedido_surtir {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-pedido-surtir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_pedido_surtir_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-pedido-surtir-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_recepcion_pedido {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-recepcion pedido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_recepcion_pedido_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-recepcion pedido-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_tarjeta_generar_folio {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-tarjeta-generar-folio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_tarjeta_generar_folio_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-tarjeta-generar-folio-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_activar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-activar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_activar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-activar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_asignar_clientes {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-asignar-clientes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_asignar_clientes_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-asignar-clientes-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_enviar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-enviar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_enviar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-enviar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_reactivar {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-reactivar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_reactivar_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-reactivar-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_suspender {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-suspender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_suspender_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-suspender-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_ver_clientes {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-ver-clientes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_vales_ver_clientes_n {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-vales-ver-clientes-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_ver_detalles {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-ver detalles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_ver_detalles_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-ver detalles-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_ver_horario {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-ver horario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_steph_vino_ver_horario_a {
            get {
                object obj = ResourceManager.GetObject("icons steph vino-ver horario-a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap light_logo_2 {
            get {
                object obj = ResourceManager.GetObject("light-logo-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Opcioens {
            get {
                object obj = ResourceManager.GetObject("Opcioens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Opcioens_1_ {
            get {
                object obj = ResourceManager.GetObject("Opcioens(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Opcioens_n {
            get {
                object obj = ResourceManager.GetObject("Opcioens-n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb01_open {
            get {
                object obj = ResourceManager.GetObject("tb01-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb02_save {
            get {
                object obj = ResourceManager.GetObject("tb02-save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb1_left {
            get {
                object obj = ResourceManager.GetObject("tb1-left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb10_color {
            get {
                object obj = ResourceManager.GetObject("tb10-color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb10_color1 {
            get {
                object obj = ResourceManager.GetObject("tb10-color1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb11_super {
            get {
                object obj = ResourceManager.GetObject("tb11-super", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb12_sub {
            get {
                object obj = ResourceManager.GetObject("tb12-sub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb2_right {
            get {
                object obj = ResourceManager.GetObject("tb2-right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb3_center {
            get {
                object obj = ResourceManager.GetObject("tb3-center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb4_bold {
            get {
                object obj = ResourceManager.GetObject("tb4-bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb5_italic {
            get {
                object obj = ResourceManager.GetObject("tb5-italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb6_underline {
            get {
                object obj = ResourceManager.GetObject("tb6-underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb7_strikeout {
            get {
                object obj = ResourceManager.GetObject("tb7-strikeout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb8_list {
            get {
                object obj = ResourceManager.GetObject("tb8-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb9_font {
            get {
                object obj = ResourceManager.GetObject("tb9-font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ver_reporte {
            get {
                object obj = ResourceManager.GetObject("ver reporte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ver_reporte_N {
            get {
                object obj = ResourceManager.GetObject("ver reporte-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ver_respuestas {
            get {
                object obj = ResourceManager.GetObject("ver-respuestas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ver_respuestas_N {
            get {
                object obj = ResourceManager.GetObject("ver-respuestas-N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
